// Pull Khand and Mukta into public/fonts and emit a local @font-face sheet.
// The fonts must be self-hosted: a phone in airplane mode cannot reach a CDN,
// and falling back to a system font loses Devanagari entirely.

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Only the weights the design actually sets. Each Devanagari face is ~90KB and
// must be precached before a phone can go offline, so unused weights are not free.
// Khand 500 stop names / 700 fares and counts. Mukta 400 body / 600 labels.
const FAMILIES = [
  { name: 'Khand', spec: 'Khand:wght@500;700', weights: ['500', '700'] },
  { name: 'Mukta', spec: 'Mukta:wght@400;600', weights: ['400', '600'] },
];
const AGENT =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const OUT = fileURLToPath(new URL('../public/fonts/', import.meta.url));

await mkdir(OUT, { recursive: true });

let sheet =
  '/* Generated by scripts/fetch-fonts.mjs. Self-hosted so the app keeps its\n   typography with no network. */\n';
let count = 0;

for (const family of FAMILIES) {
  const response = await fetch(
    `https://fonts.googleapis.com/css2?family=${family.spec}&display=swap`,
    { headers: { 'User-Agent': AGENT } },
  );
  const css = await response.text();

  for (const block of css.split('@font-face').slice(1)) {
    const url = block.match(/https:\/\/fonts\.gstatic\.com[^)]+/)?.[0];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!url || !weight || !range) continue;

    // Label by what the range actually covers, not by the comment: the comment
    // sits outside the last block and the regex would mislabel it.
    const subset = /U\+09/i.test(range) ? 'devanagari' : /U\+0100/i.test(range) ? 'latin-ext' : 'latin';
    // latin-ext is ~90KB per weight of Eastern European glyphs this app never
    // renders, and every precached byte is a byte the phone must fetch before
    // it can go offline.
    if (subset === 'latin-ext') continue;

    const file = `${family.name.toLowerCase()}-${weight}-${subset}.woff2`;
    const bytes = new Uint8Array(await (await fetch(url)).arrayBuffer());
    await writeFile(join(OUT, file), bytes);
    count += 1;

    sheet += `\n@font-face {\n  font-family: '${family.name}';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('/fonts/${file}') format('woff2');\n  unicode-range: ${range};\n}\n`;
  }
}

await writeFile(join(OUT, 'fonts.css'), sheet);
console.log(`saved ${count} woff2 files + fonts.css`);
